### ISSUE TITLE
Game foreign key violation

### ISSUE THREAD

**Issue by albinr99salt** [albinr99salt/no-name#108]
UnhandledPromiseRejectionWarning: QueryFailedError: update or delete on table "game" violates foreign key constraint "FK_46393e0d6dc5b13e2b676fe0a71" on table "player"
    at new QueryFailedError (/home/albin/projects/no-name/server/src/error/QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (/home/albin/projects/no-name/server/src/driver/postgres/PostgresQueryRunner.ts:228:19)
    at step (/home/albin/projects/no-name/server/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/home/albin/projects/no-name/server/node_modules/tslib/tslib.js:124:57)
    at rejected (/home/albin/projects/no-name/server/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by albinr99salt** [comment]
We should make sure to never get any uncaught promise rejection
